"""Application-wide constants.

Author: Rich Lewis
"""

# UI Constants
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
DATABASE_EDITOR_WIDTH = 1000
DATABASE_EDITOR_HEIGHT = 600
ICON_BUTTON_SIZE = 80
ICON_BUTTON_HEIGHT = 100
ICON_DISPLAY_SIZE = 64
ICON_GRID_COLUMNS = 8
ICON_GRID_SPACING = 10
LAYOUT_MARGINS = 5
FRAME_LINE_WIDTH = 2
EMOJI_FONT_SIZE = 48
CONTEXT_PREVIEW_LENGTH = 50

# File Operations
BACKUP_EXTENSION = ".bak"
DEFAULT_ICON_SIZE = 128
THUMBNAIL_SIZE = 64

# Search and Matching
DEFAULT_SEARCH_LIMIT = 50
DEFAULT_CONTEXT_LENGTH = 50
CONTEXT_BEFORE_MAX_CHARS = 15
CONTEXT_BEFORE_PREVIEW_LENGTH = 20
CONTEXT_AFTER_MAX_CHARS = 30
CONTEXT_AFTER_PREVIEW_LENGTH = 30
MIN_KEYWORD_LENGTH = 2
FUZZY_MATCH_THRESHOLD = 70
SIMILARITY_THRESHOLD = 50  # Default similarity threshold for duplicate detection
CRITICAL_SIMILARITY_THRESHOLD = 30
DEFAULT_ICON_SUGGESTIONS_LIMIT = 10
SEARCH_LIMIT_MULTIPLIER = 2
EXACT_EMOJI_MATCH_BONUS = 10
USAGE_COUNT_DIVISOR = 10
MAX_USAGE_COUNT_SCORE = 5
VERY_HIGH_MATCH_SCORE = 1000

# Database
MAX_KEYWORD_DISPLAY = 5
DEFAULT_EMOJI_COUNT = 200
DEFAULT_SEARCH_RESULTS_LIMIT = 10
DATABASE_TABLE_COLUMN_COUNT = 5
DEFAULT_SESSION_RETENTION_DAYS = 30
SECONDS_PER_DAY = 24 * 60 * 60

# Cache
CACHE_DIR_NAME = "emoji-cache"
ICON_CACHE_SUBDIR = "icons"
METADATA_FILENAME = "metadata.json"
DB_FILENAME = "emojis.db"

# API Configuration
API_TIMEOUT_SECONDS = 10
ICONIFY_BASE_URL = "https://api.iconify.design"
SIMPLE_ICONS_CDN_URL = "https://cdn.simpleicons.org"

# Display
MAX_DISPLAY_NAME_LENGTH = 10
FONT_SIZE_SMALL = 9

# Testing
TEST_ICON_SIZE = 64
