"""Application-wide constants.

Author: Rich Lewis
"""

# UI Constants
DEFAULT_WINDOW_WIDTH = 800
DEFAULT_WINDOW_HEIGHT = 600
ICON_BUTTON_SIZE = 80
ICON_BUTTON_HEIGHT = 100
ICON_DISPLAY_SIZE = 64
ICON_GRID_COLUMNS = 8
ICON_GRID_SPACING = 10

# File Operations
BACKUP_EXTENSION = ".bak"
DEFAULT_ICON_SIZE = 128
THUMBNAIL_SIZE = 64

# Search and Matching
DEFAULT_SEARCH_LIMIT = 50
DEFAULT_CONTEXT_LENGTH = 50
MIN_KEYWORD_LENGTH = 2
FUZZY_MATCH_THRESHOLD = 70
SIMILARITY_THRESHOLD = 60
CRITICAL_SIMILARITY_THRESHOLD = 30

# Database
MAX_KEYWORD_DISPLAY = 5
DEFAULT_EMOJI_COUNT = 200

# Cache
CACHE_DIR_NAME = "emoji-cache"
ICON_CACHE_SUBDIR = "icons"
METADATA_FILENAME = "metadata.json"

# API Configuration
API_TIMEOUT_SECONDS = 10
ICONIFY_BASE_URL = "https://api.iconify.design"
SIMPLE_ICONS_CDN_URL = "https://cdn.simpleicons.org"

# Display
MAX_DISPLAY_NAME_LENGTH = 10
FONT_SIZE_SMALL = 9

# Testing
TEST_ICON_SIZE = 64

