"""Database initialization script with 200+ curated emoji entries."""

# Local imports
from database import EmojiDatabase


def initialize_database(db_path: str = "./emoji-cache/emojis.db"):
    """Initialize the emoji database with comprehensive emoji-keyword mappings.

    This includes 200+ manually curated emojis organized by category,
    supporting many-to-many keyword mapping where multiple emojis can share keywords.

    Args:
        db_path: Path to the SQLite database file
    """
    print("Initializing emoji database...")
    db = EmojiDatabase(db_path)

    emojis_to_add = [
        # === GETTING STARTED & LAUNCH ===
        (
            "🚀",
            "rocket",
            [
                "rocket",
                "launch",
                "start",
                "deploy",
                "quick-start",
                "getting-started",
                "liftoff",
                "begin",
                "initialize",
                "kickoff",
            ],
        ),
        (
            "🎯",
            "target",
            [
                "target",
                "goal",
                "objective",
                "aim",
                "purpose",
                "focus",
                "mission",
                "milestone",
                "getting-started",
                "start",
            ],
        ),
        (
            "⚡",
            "lightning",
            [
                "lightning",
                "performance",
                "fast",
                "speed",
                "quick",
                "accelerate",
                "boost",
                "efficient",
                "quick-start",
                "rapid",
            ],
        ),
        (
            "💨",
            "dash",
            ["dash", "fast", "speed", "quick", "rapid", "swift", "performance", "zoom", "rush"],
        ),
        (
            "🏁",
            "checkered-flag",
            [
                "checkered-flag",
                "finish",
                "complete",
                "start",
                "race",
                "goal",
                "end",
                "final",
                "launch",
            ],
        ),
        (
            "▶️",
            "play",
            ["play", "start", "begin", "run", "execute", "launch", "forward", "go", "play-button"],
        ),
        # === INSTALLATION & SETUP ===
        (
            "📦",
            "package",
            [
                "package",
                "installation",
                "install",
                "setup",
                "box",
                "npm",
                "dependency",
                "module",
                "download",
                "bundle",
            ],
        ),
        (
            "⬇️",
            "download",
            [
                "download",
                "install",
                "get",
                "fetch",
                "receive",
                "arrow-down",
                "download-arrow",
                "pull",
            ],
        ),
        (
            "📥",
            "inbox",
            ["inbox", "download", "receive", "install", "import", "incoming", "tray-in", "get"],
        ),
        (
            "💾",
            "floppy-disk",
            ["floppy-disk", "save", "install", "storage", "disk", "backup", "data", "download"],
        ),
        (
            "🔽",
            "down-arrow",
            ["down-arrow", "download", "install", "dropdown", "expand", "more", "show-more"],
        ),
        (
            "⚙️",
            "settings",
            [
                "settings",
                "configuration",
                "config",
                "gear",
                "preferences",
                "setup",
                "options",
                "customize",
                "adjust",
                "install",
            ],
        ),
        (
            "🛠️",
            "tools",
            [
                "tools",
                "build",
                "construction",
                "development",
                "maintenance",
                "setup",
                "configure",
                "fix",
                "repair",
                "hammer-wrench",
            ],
        ),
        (
            "🔧",
            "wrench",
            [
                "wrench",
                "tools",
                "fix",
                "repair",
                "maintenance",
                "setup",
                "configure",
                "utilities",
                "settings",
                "adjust",
            ],
        ),
        (
            "🔨",
            "hammer",
            [
                "hammer",
                "build",
                "construction",
                "tools",
                "fix",
                "create",
                "make",
                "develop",
                "forge",
            ],
        ),
        (
            "⚒️",
            "hammer-pick",
            ["hammer-pick", "tools", "build", "mining", "construction", "development", "create"],
        ),
        # === DOCUMENTATION ===
        (
            "📝",
            "memo",
            [
                "memo",
                "documentation",
                "docs",
                "notes",
                "writing",
                "edit",
                "readme",
                "instructions",
                "pencil",
                "record",
            ],
        ),
        (
            "📄",
            "document",
            [
                "document",
                "page",
                "file",
                "docs",
                "documentation",
                "paper",
                "readme",
                "text",
                "content",
            ],
        ),
        (
            "📃",
            "page-curl",
            ["page-curl", "document", "file", "docs", "text", "paper", "content", "readme"],
        ),
        (
            "📖",
            "book-open",
            [
                "book-open",
                "documentation",
                "reading",
                "manual",
                "guide",
                "readme",
                "docs",
                "learn",
                "reference",
            ],
        ),
        (
            "📚",
            "books",
            [
                "books",
                "library",
                "documentation",
                "resources",
                "learning",
                "education",
                "knowledge",
                "guides",
                "reference",
                "docs",
            ],
        ),
        (
            "📋",
            "clipboard",
            [
                "clipboard",
                "list",
                "checklist",
                "tasks",
                "todo",
                "items",
                "plan",
                "agenda",
                "notes",
                "copy",
            ],
        ),
        (
            "📑",
            "bookmark-tabs",
            ["bookmark-tabs", "documentation", "reference", "tabs", "pages", "organize", "docs"],
        ),
        (
            "🗒️",
            "notepad",
            ["notepad", "notes", "memo", "documentation", "writing", "docs", "text", "pad"],
        ),
        (
            "📓",
            "notebook",
            ["notebook", "notes", "documentation", "journal", "writing", "docs", "book", "log"],
        ),
        (
            "📔",
            "notebook-decorated",
            ["notebook-decorated", "notes", "documentation", "journal", "writing", "book"],
        ),
        (
            "📕",
            "closed-book",
            ["closed-book", "documentation", "book", "manual", "guide", "reference", "red-book"],
        ),
        (
            "📗",
            "green-book",
            ["green-book", "documentation", "book", "manual", "guide", "reference"],
        ),
        ("📘", "blue-book", ["blue-book", "documentation", "book", "manual", "guide", "reference"]),
        (
            "📙",
            "orange-book",
            ["orange-book", "documentation", "book", "manual", "guide", "reference"],
        ),
        # === FEATURES & HIGHLIGHTS ===
        (
            "✨",
            "sparkles",
            [
                "sparkles",
                "features",
                "new",
                "special",
                "highlights",
                "enhancements",
                "improvements",
                "shine",
                "stars",
            ],
        ),
        (
            "🌟",
            "star",
            [
                "star",
                "favorite",
                "featured",
                "important",
                "highlight",
                "bookmark",
                "rating",
                "quality",
                "glowing-star",
            ],
        ),
        (
            "⭐",
            "star-solid",
            [
                "star-solid",
                "favorite",
                "featured",
                "important",
                "rating",
                "highlight",
                "bookmark",
                "quality",
            ],
        ),
        (
            "💫",
            "dizzy",
            ["dizzy", "features", "sparkle", "magic", "special", "shine", "stars", "effects"],
        ),
        (
            "🎆",
            "fireworks",
            [
                "fireworks",
                "celebration",
                "features",
                "special",
                "exciting",
                "launch",
                "new",
                "spectacular",
            ],
        ),
        (
            "🎇",
            "sparkler",
            ["sparkler", "celebration", "features", "sparkle", "special", "shine", "new"],
        ),
        (
            "✴️",
            "eight-pointed-star",
            ["eight-pointed-star", "feature", "special", "highlight", "star", "important"],
        ),
        ("❇️", "sparkle", ["sparkle", "feature", "highlight", "special", "shine", "star", "new"]),
        # === SUCCESS & COMPLETION ===
        (
            "✅",
            "check-mark-button",
            [
                "check-mark-button",
                "done",
                "success",
                "completed",
                "verified",
                "approved",
                "valid",
                "correct",
                "confirmed",
                "yes",
            ],
        ),
        (
            "✔️",
            "check-mark",
            [
                "check-mark",
                "done",
                "success",
                "complete",
                "approved",
                "valid",
                "correct",
                "yes",
                "tick",
            ],
        ),
        (
            "☑️",
            "checked-box",
            [
                "checked-box",
                "done",
                "complete",
                "success",
                "checkbox",
                "selected",
                "yes",
                "verified",
            ],
        ),
        (
            "🎉",
            "party-popper",
            [
                "party-popper",
                "celebration",
                "success",
                "congratulations",
                "launch",
                "release",
                "achievement",
                "hooray",
                "tada",
            ],
        ),
        (
            "🎊",
            "confetti-ball",
            [
                "confetti-ball",
                "celebration",
                "party",
                "success",
                "congratulations",
                "achievement",
                "festive",
            ],
        ),
        (
            "🥳",
            "partying-face",
            ["partying-face", "celebration", "party", "success", "happy", "festive", "excited"],
        ),
        (
            "🏆",
            "trophy",
            [
                "trophy",
                "achievement",
                "winner",
                "award",
                "success",
                "champion",
                "prize",
                "first-place",
                "best",
            ],
        ),
        (
            "🥇",
            "first-place",
            [
                "first-place",
                "winner",
                "gold",
                "medal",
                "achievement",
                "champion",
                "best",
                "top",
                "number-one",
            ],
        ),
        ("🥈", "second-place", ["second-place", "silver", "medal", "achievement", "runner-up"]),
        ("🥉", "third-place", ["third-place", "bronze", "medal", "achievement"]),
        ("🏅", "medal", ["medal", "achievement", "award", "winner", "success", "badge", "honor"]),
        # === ERRORS & WARNINGS ===
        (
            "❌",
            "cross-mark",
            [
                "cross-mark",
                "error",
                "failed",
                "wrong",
                "remove",
                "delete",
                "cancel",
                "invalid",
                "incorrect",
                "rejected",
                "no",
            ],
        ),
        (
            "❎",
            "cross-mark-button",
            ["cross-mark-button", "error", "failed", "wrong", "no", "cancel", "remove", "invalid"],
        ),
        (
            "✖️",
            "multiply",
            ["multiply", "close", "error", "remove", "delete", "cancel", "wrong", "x"],
        ),
        (
            "🚫",
            "prohibited",
            [
                "prohibited",
                "error",
                "forbidden",
                "no",
                "ban",
                "stop",
                "not-allowed",
                "restricted",
                "blocked",
            ],
        ),
        (
            "⛔",
            "no-entry",
            ["no-entry", "error", "stop", "forbidden", "prohibited", "blocked", "restricted"],
        ),
        (
            "🛑",
            "stop-sign",
            ["stop-sign", "error", "stop", "halt", "warning", "critical", "emergency", "cease"],
        ),
        (
            "⚠️",
            "warning",
            [
                "warning",
                "caution",
                "alert",
                "attention",
                "important",
                "notice",
                "exclamation",
                "careful",
            ],
        ),
        (
            "🚨",
            "police-light",
            [
                "police-light",
                "alert",
                "warning",
                "emergency",
                "urgent",
                "critical",
                "siren",
                "alarm",
            ],
        ),
        (
            "🚧",
            "construction",
            [
                "construction",
                "warning",
                "work-in-progress",
                "WIP",
                "caution",
                "development",
                "under-construction",
                "building",
            ],
        ),
        (
            "🔴",
            "red-circle",
            ["red-circle", "error", "stop", "critical", "live", "recording", "alert", "important"],
        ),
        (
            "🐛",
            "bug",
            [
                "bug",
                "issue",
                "debug",
                "error",
                "problem",
                "defect",
                "glitch",
                "troubleshoot",
                "fix",
                "insect",
            ],
        ),
        ("🪲", "beetle", ["beetle", "bug", "issue", "error", "problem", "glitch", "insect"]),
        ("🐞", "ladybug", ["ladybug", "bug", "issue", "error", "cute-bug", "problem"]),
        # === INFORMATION & TIPS ===
        (
            "ℹ️",
            "information",
            [
                "information",
                "info",
                "about",
                "help",
                "details",
                "notice",
                "tip",
                "learn",
                "knowledge",
            ],
        ),
        (
            "💡",
            "lightbulb",
            [
                "lightbulb",
                "idea",
                "tip",
                "suggestion",
                "insight",
                "innovation",
                "concept",
                "hint",
                "thinking",
                "solution",
            ],
        ),
        (
            "💭",
            "thought-bubble",
            [
                "thought-bubble",
                "idea",
                "thinking",
                "concept",
                "suggestion",
                "wondering",
                "contemplation",
            ],
        ),
        (
            "🗨️",
            "speech-bubble-left",
            [
                "speech-bubble-left",
                "comment",
                "message",
                "chat",
                "talk",
                "communication",
                "say",
                "discuss",
            ],
        ),
        (
            "💬",
            "speech-balloon",
            ["speech-balloon", "comment", "message", "chat", "communication", "talk", "discussion"],
        ),
        (
            "🗯️",
            "anger-bubble",
            ["anger-bubble", "comment", "emphasis", "strong", "important", "statement"],
        ),
        (
            "📢",
            "loudspeaker",
            [
                "loudspeaker",
                "announcement",
                "broadcast",
                "news",
                "alert",
                "notice",
                "public",
                "megaphone",
            ],
        ),
        (
            "📣",
            "megaphone",
            ["megaphone", "announcement", "broadcast", "loud", "alert", "news", "public", "shout"],
        ),
        (
            "📌",
            "pushpin",
            ["pushpin", "note", "pin", "important", "highlight", "bookmark", "attach", "mark"],
        ),
        (
            "📍",
            "location-pin",
            ["location-pin", "location", "place", "marker", "position", "map", "geo", "point"],
        ),
        # === CODE & DEVELOPMENT ===
        (
            "💻",
            "laptop",
            [
                "laptop",
                "computer",
                "code",
                "programming",
                "development",
                "software",
                "tech",
                "coding",
                "dev",
            ],
        ),
        (
            "🖥️",
            "desktop-computer",
            [
                "desktop-computer",
                "computer",
                "code",
                "programming",
                "development",
                "workstation",
                "monitor",
                "pc",
            ],
        ),
        (
            "⌨️",
            "keyboard",
            ["keyboard", "typing", "code", "input", "programming", "development", "write", "type"],
        ),
        ("🖱️", "mouse", ["mouse", "computer", "click", "input", "pointer", "cursor", "device"]),
        ("🖨️", "printer", ["printer", "print", "output", "document", "paper", "copy", "device"]),
        (
            "🔌",
            "plug",
            ["plug", "power", "connection", "electric", "plugin", "extension", "connect"],
        ),
        (
            "🔋",
            "battery",
            ["battery", "power", "energy", "charge", "electricity", "fuel", "capacity"],
        ),
        ("💿", "cd", ["cd", "disk", "storage", "media", "optical", "data", "disc"]),
        ("📀", "dvd", ["dvd", "disk", "storage", "media", "optical", "data", "blue-disc"]),
        (
            "🧑‍💻",
            "technologist",
            [
                "technologist",
                "developer",
                "programmer",
                "coder",
                "software-engineer",
                "dev",
                "coding",
            ],
        ),
        (
            "👨‍💻",
            "man-technologist",
            ["man-technologist", "developer", "programmer", "male-coder", "software-engineer"],
        ),
        (
            "👩‍💻",
            "woman-technologist",
            ["woman-technologist", "developer", "programmer", "female-coder", "software-engineer"],
        ),
        # === TESTING & QA ===
        (
            "🧪",
            "test-tube",
            [
                "test-tube",
                "test",
                "testing",
                "experiment",
                "lab",
                "science",
                "unittest",
                "QA",
                "validation",
                "trial",
                "verify",
            ],
        ),
        (
            "🔬",
            "microscope",
            [
                "microscope",
                "test",
                "testing",
                "analyze",
                "inspection",
                "examine",
                "science",
                "research",
                "detailed",
            ],
        ),
        (
            "🧬",
            "dna",
            ["dna", "test", "genetic", "code", "science", "structure", "biology", "molecular"],
        ),
        (
            "🔍",
            "magnifying-glass-left",
            [
                "magnifying-glass-left",
                "search",
                "find",
                "inspect",
                "examine",
                "look",
                "explore",
                "investigate",
                "zoom",
                "test",
            ],
        ),
        (
            "🔎",
            "magnifying-glass-right",
            [
                "magnifying-glass-right",
                "search",
                "find",
                "inspect",
                "examine",
                "investigate",
                "zoom",
                "test",
            ],
        ),
        (
            "🕵️",
            "detective",
            ["detective", "investigate", "search", "inspect", "test", "examine", "spy", "sleuth"],
        ),
        (
            "👀",
            "eyes",
            [
                "eyes",
                "watching",
                "observe",
                "inspect",
                "look",
                "see",
                "review",
                "viewing",
                "attention",
            ],
        ),
        # === SECURITY & PRIVACY ===
        (
            "🔒",
            "locked",
            [
                "locked",
                "security",
                "private",
                "secure",
                "protected",
                "encrypted",
                "closed",
                "safe",
                "auth",
            ],
        ),
        (
            "🔓",
            "unlocked",
            ["unlocked", "open", "accessible", "public", "unsecure", "access", "available"],
        ),
        (
            "🔐",
            "locked-key",
            [
                "locked-key",
                "secure",
                "security",
                "encryption",
                "protected",
                "private",
                "authenticated",
                "safe",
            ],
        ),
        (
            "🔏",
            "locked-pen",
            ["locked-pen", "security", "signature", "signed", "secure-document", "protected"],
        ),
        (
            "🔑",
            "key",
            [
                "key",
                "password",
                "access",
                "credential",
                "token",
                "unlock",
                "authorization",
                "secret",
                "auth",
                "login",
            ],
        ),
        (
            "🗝️",
            "old-key",
            ["old-key", "key", "password", "access", "unlock", "legacy", "vintage", "secret"],
        ),
        (
            "🛡️",
            "shield",
            [
                "shield",
                "security",
                "protection",
                "defend",
                "guard",
                "safe",
                "firewall",
                "defense",
                "secure",
            ],
        ),
        (
            "🛟",
            "lifebuoy",
            ["lifebuoy", "help", "safety", "rescue", "support", "protection", "emergency", "save"],
        ),
        (
            "🚪",
            "door",
            ["door", "access", "entry", "entrance", "exit", "gateway", "portal", "login", "logout"],
        ),
        (
            "🪪",
            "id-card",
            [
                "id-card",
                "identification",
                "credential",
                "badge",
                "identity",
                "profile",
                "user",
                "auth",
            ],
        ),
        # === DATA & ANALYTICS ===
        (
            "📊",
            "bar-chart",
            [
                "bar-chart",
                "analytics",
                "stats",
                "data",
                "metrics",
                "dashboard",
                "report",
                "graph",
                "statistics",
                "insights",
            ],
        ),
        (
            "📈",
            "chart-increasing",
            [
                "chart-increasing",
                "growth",
                "increase",
                "trending-up",
                "improvement",
                "progress",
                "rising",
                "gain",
                "up",
            ],
        ),
        (
            "📉",
            "chart-decreasing",
            [
                "chart-decreasing",
                "decline",
                "decrease",
                "trending-down",
                "reduction",
                "drop",
                "falling",
                "down",
            ],
        ),
        (
            "🗃️",
            "card-file-box",
            [
                "card-file-box",
                "database",
                "storage",
                "archive",
                "records",
                "data",
                "filing",
                "organized",
            ],
        ),
        (
            "🗄️",
            "file-cabinet",
            [
                "file-cabinet",
                "storage",
                "archive",
                "database",
                "files",
                "records",
                "data",
                "organized",
            ],
        ),
        ("💽", "minidisc", ["minidisc", "data", "storage", "disk", "media", "optical"]),
        (
            "💼",
            "briefcase",
            [
                "briefcase",
                "business",
                "work",
                "professional",
                "case",
                "data",
                "documents",
                "office",
            ],
        ),
        # === NETWORK & WEB ===
        (
            "🌐",
            "globe-meridians",
            [
                "globe-meridians",
                "global",
                "web",
                "internet",
                "worldwide",
                "i18n",
                "international",
                "online",
                "network",
                "world",
            ],
        ),
        (
            "🌍",
            "earth-europe-africa",
            [
                "earth-europe-africa",
                "global",
                "world",
                "international",
                "worldwide",
                "planet",
                "geography",
            ],
        ),
        (
            "🌎",
            "earth-americas",
            [
                "earth-americas",
                "global",
                "world",
                "international",
                "worldwide",
                "planet",
                "western",
            ],
        ),
        (
            "🌏",
            "earth-asia-australia",
            [
                "earth-asia-australia",
                "global",
                "world",
                "international",
                "worldwide",
                "planet",
                "eastern",
            ],
        ),
        (
            "🗺️",
            "world-map",
            [
                "world-map",
                "global",
                "geography",
                "travel",
                "international",
                "navigation",
                "location",
                "map",
            ],
        ),
        (
            "🧭",
            "compass",
            ["compass", "navigation", "direction", "orientation", "map", "travel", "explore"],
        ),
        (
            "📡",
            "satellite-antenna",
            [
                "satellite-antenna",
                "network",
                "communication",
                "broadcast",
                "signal",
                "wireless",
                "connection",
                "transmission",
            ],
        ),
        (
            "📶",
            "signal-strength",
            [
                "signal-strength",
                "network",
                "wifi",
                "connection",
                "bars",
                "wireless",
                "connectivity",
                "cellular",
            ],
        ),
        (
            "📳",
            "vibration-mode",
            ["vibration-mode", "mobile", "phone", "notification", "alert", "silent", "buzz"],
        ),
        (
            "📴",
            "mobile-phone-off",
            ["mobile-phone-off", "offline", "disconnected", "no-signal", "airplane-mode"],
        ),
        (
            "🔗",
            "link",
            [
                "link",
                "url",
                "hyperlink",
                "connection",
                "chain",
                "reference",
                "href",
                "anchor",
                "connect",
            ],
        ),
        (
            "⛓️",
            "chains",
            ["chains", "link", "connection", "blockchain", "connected", "bound", "constraint"],
        ),
        # === FILES & FOLDERS ===
        (
            "📁",
            "folder",
            [
                "folder",
                "directory",
                "files",
                "organize",
                "storage",
                "container",
                "open-folder",
                "file-system",
            ],
        ),
        (
            "📂",
            "open-folder",
            ["open-folder", "directory", "files", "access", "storage", "explore", "file-system"],
        ),
        (
            "🗂️",
            "card-index-dividers",
            [
                "card-index-dividers",
                "organize",
                "files",
                "tabs",
                "categories",
                "sorting",
                "filing",
                "indexed",
            ],
        ),
        (
            "📇",
            "card-index",
            ["card-index", "contacts", "database", "records", "rolodex", "organized", "filing"],
        ),
        (
            "🗑️",
            "wastebasket",
            ["wastebasket", "delete", "trash", "remove", "discard", "bin", "garbage", "recycle"],
        ),
        (
            "♻️",
            "recycle",
            ["recycle", "reuse", "refresh", "restore", "renew", "circular", "green", "sustainable"],
        ),
        # === COMMUNICATION & MESSAGING ===
        (
            "📧",
            "email",
            ["email", "mail", "message", "communication", "letter", "contact", "inbox", "send"],
        ),
        (
            "📨",
            "incoming-envelope",
            ["incoming-envelope", "email", "message", "received", "mail", "inbox", "notification"],
        ),
        (
            "📩",
            "envelope-arrow",
            ["envelope-arrow", "email", "send", "message", "outgoing", "mail", "forward"],
        ),
        (
            "📬",
            "open-mailbox",
            ["open-mailbox", "email", "received", "mail", "inbox", "messages", "flag-up"],
        ),
        (
            "📭",
            "closed-mailbox",
            ["closed-mailbox", "email", "empty", "mail", "no-messages", "flag-down"],
        ),
        ("📮", "postbox", ["postbox", "mail", "send", "email", "post", "letter", "drop-box"]),
        (
            "✉️",
            "envelope",
            ["envelope", "email", "mail", "message", "letter", "send", "communication"],
        ),
        (
            "💌",
            "love-letter",
            [
                "love-letter",
                "email",
                "message",
                "heart",
                "romantic",
                "affection",
                "special-message",
            ],
        ),
        (
            "📞",
            "telephone-receiver",
            ["telephone-receiver", "phone", "call", "contact", "communication", "dial", "ring"],
        ),
        (
            "📱",
            "mobile-phone",
            [
                "mobile-phone",
                "smartphone",
                "device",
                "cellular",
                "app",
                "mobile",
                "phone",
                "ios",
                "android",
                "responsive",
            ],
        ),
        (
            "📲",
            "mobile-arrow",
            ["mobile-arrow", "phone", "call", "contact", "incoming-call", "receive"],
        ),
        # === TIME & SCHEDULING ===
        (
            "⏰",
            "alarm-clock",
            [
                "alarm-clock",
                "time",
                "clock",
                "schedule",
                "deadline",
                "timer",
                "reminder",
                "alert",
                "wake",
            ],
        ),
        (
            "⏱️",
            "stopwatch",
            ["stopwatch", "time", "timer", "measure", "duration", "timing", "countdown", "track"],
        ),
        (
            "⏲️",
            "timer-clock",
            ["timer-clock", "time", "countdown", "alarm", "schedule", "cooking-timer", "duration"],
        ),
        (
            "⌚",
            "watch",
            ["watch", "time", "clock", "wearable", "schedule", "timepiece", "wristwatch"],
        ),
        (
            "📅",
            "calendar",
            [
                "calendar",
                "date",
                "schedule",
                "event",
                "appointment",
                "day",
                "month",
                "planning",
                "agenda",
            ],
        ),
        (
            "📆",
            "tear-off-calendar",
            ["tear-off-calendar", "date", "schedule", "day", "event", "daily", "planning"],
        ),
        (
            "🗓️",
            "spiral-calendar",
            [
                "spiral-calendar",
                "calendar",
                "schedule",
                "date",
                "planning",
                "notebook-calendar",
                "agenda",
            ],
        ),
        # === DESIGN & CREATIVITY ===
        (
            "🎨",
            "artist-palette",
            [
                "artist-palette",
                "design",
                "art",
                "color",
                "creative",
                "paint",
                "style",
                "theme",
                "ui",
                "interface",
                "aesthetic",
            ],
        ),
        (
            "🖌️",
            "paintbrush",
            ["paintbrush", "design", "art", "paint", "creative", "drawing", "brush", "artistic"],
        ),
        (
            "🖍️",
            "crayon",
            ["crayon", "design", "art", "draw", "color", "creative", "sketch", "colorful"],
        ),
        (
            "✏️",
            "pencil",
            ["pencil", "edit", "write", "draw", "design", "draft", "sketch", "modify", "compose"],
        ),
        ("✒️", "pen", ["pen", "write", "edit", "signature", "ink", "compose", "writing", "formal"]),
        (
            "🖊️",
            "pen-ballpoint",
            ["pen-ballpoint", "write", "edit", "writing", "compose", "document", "note"],
        ),
        (
            "🖋️",
            "pen-fountain",
            [
                "pen-fountain",
                "write",
                "signature",
                "elegant",
                "compose",
                "formal-writing",
                "calligraphy",
            ],
        ),
        (
            "📐",
            "triangular-ruler",
            [
                "triangular-ruler",
                "design",
                "measure",
                "geometry",
                "angle",
                "precision",
                "architecture",
            ],
        ),
        ("📏", "ruler", ["ruler", "measure", "design", "straight", "length", "precision", "scale"]),
        # === BUILD & DEPLOYMENT ===
        (
            "🏗️",
            "building-construction",
            [
                "building-construction",
                "architecture",
                "structure",
                "building",
                "framework",
                "infrastructure",
                "scaffold",
                "build",
                "construct",
            ],
        ),
        (
            "🏭",
            "factory",
            [
                "factory",
                "build",
                "production",
                "manufacturing",
                "industry",
                "process",
                "output",
                "compile",
            ],
        ),
        (
            "🔩",
            "nut-bolt",
            ["nut-bolt", "build", "hardware", "mechanical", "assembly", "fastener", "connection"],
        ),
        (
            "🪛",
            "screwdriver",
            ["screwdriver", "build", "tools", "fix", "adjust", "repair", "assembly", "tighten"],
        ),
        ("🪚", "saw", ["saw", "build", "cut", "tools", "construction", "carpentry", "wood"]),
        ("⛏️", "pick", ["pick", "build", "mining", "digging", "tool", "excavate", "minecraft"]),
        # === VERSION CONTROL & GIT ===
        (
            "🔀",
            "shuffle",
            ["shuffle", "merge", "branch", "mix", "random", "change", "git-merge", "combine"],
        ),
        (
            "🔁",
            "repeat",
            ["repeat", "sync", "refresh", "loop", "cycle", "reload", "retry", "again"],
        ),
        ("🔂", "repeat-one", ["repeat-one", "loop", "single", "replay", "again", "once-more"]),
        (
            "🔄",
            "refresh",
            ["refresh", "reload", "sync", "update", "renew", "rotate", "clockwise", "refresh-page"],
        ),
        (
            "↩️",
            "back-arrow",
            ["back-arrow", "undo", "return", "revert", "back", "previous", "rollback"],
        ),
        ("↪️", "forward-arrow", ["forward-arrow", "redo", "forward", "next", "proceed", "continue"]),
        (
            "⬆️",
            "up-arrow",
            ["up-arrow", "upload", "increase", "upgrade", "up", "ascend", "deploy", "push"],
        ),
        (
            "⬇️",
            "down-arrow-symbol",
            ["down-arrow", "download", "decrease", "downgrade", "down", "descend", "pull"],
        ),
        (
            "➡️",
            "right-arrow",
            ["right-arrow", "next", "forward", "continue", "proceed", "right", "advance"],
        ),
        (
            "⬅️",
            "left-arrow",
            ["left-arrow", "back", "previous", "return", "left", "rewind", "backward"],
        ),
        ("🔼", "up-button", ["up-button", "increase", "upload", "scroll-up", "move-up", "upward"]),
        (
            "🌿",
            "herb",
            ["herb", "branch", "git-branch", "green", "nature", "leaf", "natural", "organic"],
        ),
        (
            "🌱",
            "seedling",
            ["seedling", "new", "grow", "start", "sprout", "beginning", "fresh", "green", "young"],
        ),
        (
            "🌳",
            "deciduous-tree",
            [
                "deciduous-tree",
                "branch",
                "tree",
                "structure",
                "hierarchy",
                "root",
                "trunk",
                "tree-structure",
            ],
        ),
        # === PERFORMANCE & OPTIMIZATION ===
        (
            "🏎️",
            "race-car",
            ["race-car", "fast", "speed", "performance", "racing", "quick", "sport", "velocity"],
        ),
        (
            "🏃",
            "running",
            ["running", "fast", "quick", "active", "speed", "sprint", "hurry", "dash"],
        ),
        (
            "⏩",
            "fast-forward",
            ["fast-forward", "skip", "quick", "speed", "fast", "accelerate", "advance", "next"],
        ),
        ("⏭️", "next-track", ["next-track", "skip", "next", "forward", "advance", "fast-forward"]),
        (
            "🔥",
            "fire",
            [
                "fire",
                "hot",
                "trending",
                "popular",
                "performance",
                "fast",
                "burning",
                "flame",
                "active",
            ],
        ),
        (
            "💪",
            "muscle",
            [
                "muscle",
                "strong",
                "powerful",
                "strength",
                "performance",
                "robust",
                "flex",
                "capable",
            ],
        ),
        # === COLLABORATION & TEAM ===
        (
            "🤝",
            "handshake",
            [
                "handshake",
                "partnership",
                "collaboration",
                "agreement",
                "teamwork",
                "cooperation",
                "deal",
                "alliance",
                "meeting",
            ],
        ),
        (
            "👥",
            "people",
            [
                "people",
                "team",
                "group",
                "users",
                "collaboration",
                "community",
                "members",
                "collective",
                "crowd",
            ],
        ),
        (
            "👫",
            "couple",
            ["couple", "pair", "team", "partnership", "duo", "together", "collaboration"],
        ),
        (
            "👬",
            "men-holding-hands",
            ["men-holding-hands", "team", "partnership", "collaboration", "male-team", "pair"],
        ),
        (
            "👭",
            "women-holding-hands",
            ["women-holding-hands", "team", "partnership", "collaboration", "female-team", "pair"],
        ),
        (
            "🗣️",
            "speaking-head",
            ["speaking-head", "communication", "discussion", "voice", "speak", "talk", "announce"],
        ),
        # === LEARNING & EDUCATION ===
        (
            "🎓",
            "graduation-cap",
            [
                "graduation-cap",
                "education",
                "learning",
                "academic",
                "graduate",
                "school",
                "degree",
                "course",
                "study",
                "tutorial",
            ],
        ),
        (
            "🏫",
            "school",
            ["school", "education", "learning", "academy", "institution", "campus", "university"],
        ),
        (
            "🎒",
            "backpack",
            ["backpack", "school", "education", "student", "learning", "bag", "supplies"],
        ),
        # === UI ELEMENTS & CONTROLS ===
        (
            "⏸️",
            "pause-button",
            ["pause-button", "pause", "stop", "hold", "wait", "suspend", "interrupt"],
        ),
        (
            "⏹️",
            "stop-button",
            ["stop-button", "stop", "end", "terminate", "halt", "cease", "finish"],
        ),
        (
            "⏺️",
            "record-button",
            ["record-button", "record", "capture", "save", "log", "start-recording", "rec"],
        ),
        (
            "⏏️",
            "eject-button",
            ["eject-button", "eject", "remove", "disconnect", "unmount", "extract"],
        ),
        (
            "⏮️",
            "previous-track",
            ["previous-track", "back", "previous", "rewind", "last", "backward"],
        ),
        ("⏪", "rewind", ["rewind", "back", "reverse", "previous", "backward", "replay"]),
        (
            "🔃",
            "clockwise-arrows",
            ["clockwise-arrows", "refresh", "reload", "sync", "rotate", "cycle", "update"],
        ),
        (
            "🔆",
            "bright",
            ["bright", "brightness-up", "increase-brightness", "light", "sun", "high"],
        ),
        ("🔅", "dim", ["dim", "brightness-down", "decrease-brightness", "low", "dark"]),
        # === STATUS & INDICATORS ===
        (
            "🟢",
            "green-circle",
            ["green-circle", "online", "active", "success", "go", "available", "running", "live"],
        ),
        (
            "🟡",
            "yellow-circle",
            ["yellow-circle", "warning", "caution", "pending", "wait", "in-progress", "pause"],
        ),
        ("🟠", "orange-circle", ["orange-circle", "warning", "moderate", "caution", "alert"]),
        (
            "🔵",
            "blue-circle",
            ["blue-circle", "info", "information", "active", "selected", "default"],
        ),
        ("🟣", "purple-circle", ["purple-circle", "special", "premium", "featured", "unique"]),
        ("⚫", "black-circle", ["black-circle", "off", "inactive", "disabled", "stopped"]),
        ("⚪", "white-circle", ["white-circle", "empty", "unselected", "blank", "off"]),
        ("🟤", "brown-circle", ["brown-circle", "neutral", "earth", "organic"]),
        (
            "🔘",
            "radio-button",
            ["radio-button", "selected", "option", "choice", "selected-radio", "active"],
        ),
        ("⭕", "hollow-circle", ["hollow-circle", "empty", "unselected", "ring", "circle", "zero"]),
        ("⬜", "white-square", ["white-square", "unchecked", "empty", "blank", "unselected"]),
        (
            "◻️",
            "white-square-small",
            ["white-square-small", "checkbox", "unchecked", "empty", "unselected"],
        ),
        # === POPULAR & TRENDING ===
        (
            "💯",
            "hundred-points",
            [
                "hundred-points",
                "perfect",
                "top",
                "excellent",
                "100",
                "full-score",
                "complete",
                "best",
            ],
        ),
        (
            "👍",
            "thumbs-up",
            ["thumbs-up", "like", "approve", "good", "yes", "agree", "positive", "upvote"],
        ),
        (
            "👏",
            "clapping",
            [
                "clapping",
                "applause",
                "congratulations",
                "appreciation",
                "bravo",
                "praise",
                "well-done",
            ],
        ),
        ("❤️", "red-heart", ["red-heart", "love", "favorite", "like", "popular", "passion", "care"]),
        (
            "💖",
            "sparkling-heart",
            ["sparkling-heart", "love", "favorite", "special", "sparkle", "affection"],
        ),
        (
            "🎖️",
            "military-medal",
            ["military-medal", "achievement", "award", "recognition", "honor", "badge"],
        ),
        # === MISCELLANEOUS COMMON ===
        (
            "🏷️",
            "label",
            ["label", "tag", "price", "category", "name", "metadata", "classification", "badge"],
        ),
        ("🎁", "gift", ["gift", "present", "reward", "bonus", "package", "wrapped", "surprise"]),
        ("🎈", "balloon", ["balloon", "celebration", "party", "festive", "fun", "event", "happy"]),
        (
            "🔖",
            "bookmark",
            ["bookmark", "save", "mark", "reference", "saved", "tag", "favorite", "remember"],
        ),
        (
            "🎚️",
            "slider",
            ["slider", "control", "adjust", "volume", "settings", "level", "parameter"],
        ),
        (
            "🎛️",
            "control-knobs",
            ["control-knobs", "settings", "adjust", "controls", "mixer", "parameters"],
        ),
    ]

    count = 0
    for unicode, common_name, keywords in emojis_to_add:
        if db.add_emoji(unicode, common_name, keywords):
            count += 1

    print(f"Successfully added {count} emojis to the database!")
    print(f"Database location: {db_path}")

    db.close()
    return count


if __name__ == "__main__":
    # Initialize database when run as script
    count = initialize_database()
    print(f"\n✅ Database initialized with {count} emoji entries!")
    print("The program is ready to use.")
